name: MySchool
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  file_picker: ^10.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_native_splash: ^2.4.6
  get_it: ^8.0.3
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.18.1
  jwt_decoder: ^2.0.1
  open_file: ^3.5.10
  path_provider: ^2.1.1
  pdf: ^3.10.7
  permission_handler: ^12.0.0+1
  rflutter_alert: ^2.0.7
  shared_preferences: ^2.2.2
  timeago: ^3.7.1
  timezone: ^0.10.1
  uuid: ^4.5.1
  timeline_tile: ^2.0.0


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
